### ISSUE TITLE
Error used inside package

### ISSUE THREAD

**Issue by DeveloperPaul123** [jomaway/typst-linguify#6]
I'm trying to use this package in a template I have published and am getting the following error:

```bash
error: dictionary does not contain key "conf"
   ┌─ @preview/linguify:0.4.0\lib\linguify.typ:73:27
   │
73 │   let data_type = database.conf.at("data_type", default: "dict")
   │                            ^^^^

help: error occurred in this call of function `_linguify`
    ┌─ @preview/linguify:0.4.0\lib\linguify.typ:136:17
    │
136 │     let result = _linguify(key, from: from, lang: lang, args: args)
    │                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

**Comment by DeveloperPaul123** [comment]
Here's my code and data:

```typst
let lang_data = toml("lang.toml")

  set document(
    author: author.firstname + " " + author.lastname,
    title: linguify(resume, from: lang_data),
  )
```
`lang.toml`
```toml
default-lang = "en"

[en]
resume = "Résumé"
dear = "Dear"
cover-letter = "Cover Letter"

[de]
resume = "Lebenslauf"
dear = "Sehr geehrte"
cover-letter = "Bewerbungsschreiben"
```
